--LSP reference: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification
--lsp logs to ~/.local/state/nvim/lsp.log
--vim.lsp.log.set_level('debug')
--require('vim.lsp.log').set_format_func(vim.inspect)
--find filetypes and their names via commend :e $VIMRUNTIME/lua/vim/filetype.lua

--
--lsp_zero.on_attach(function(client, bufnr)
--    local opts = { buffer = bufnr, remap = false }
--
--    vim.keymap.set("n", "<leader>f", function() vim.lsp.buf.format() end)
--    vim.keymap.set("n", "gd", function() vim.lsp.buf.definition() end, opts)
--    vim.keymap.set("n", "K", function() vim.lsp.buf.hover() end, opts)
--    --vim.keymap.set("n", "<leader>vws", function() vim.lsp.buf.definition() end, opts) -- TODO: doesn't do anthing
--    vim.keymap.set("n", "<leader>vca", function() vim.lsp.buf.code_action() end, opts)
--    vim.keymap.set("n", "<leader>vrr", function() vim.lsp.buf.references() end, opts)
--    vim.keymap.set("n", "<leader>vrn", function() vim.lsp.buf.rename() end, opts)
--    vim.keymap.set("i", "<C-h>", function() vim.lsp.buf.signature_help() end, opts)
--end)
